refactor(mshot): replace `still` with  `wayfreeze` for freezing

diff --git a/mshot/mshot b/mshot/mshot
--- a/mshot/mshot
+++ b/mshot/mshot
@@ -41,10 +41,18 @@ root_command() {
   fi
 
   if [[ ${args[--freeze]} ]]; then
+    cursor_flag=""
+    [[ -z $use_pointer ]] && cursor_flag="--hide-cursor"
     if [[ ${args[--region]} ]]; then
-      still ${use_pointer:+-p} -c "slurp -d | $(printf '%q ' "${cmd[@]}")-g- $(printf '%q' "$filepath")"
+      wayfreeze $cursor_flag & PID=$!
+      sleep .1
+      slurp -d | "${cmd[@]}" -g- "$filepath"
+      kill $PID 2>/dev/null || true
     else
-      still ${use_pointer:+-p} -c "$(printf '%q ' "${cmd[@]}")$(printf '%q' "$filepath")"
+      wayfreeze $cursor_flag & PID=$!
+      sleep .1
+      "${cmd[@]}" "$filepath"
+      kill $PID 2>/dev/null || true
     fi
   elif [[ ${args[--region]} ]]; then
     slurp -d | "${cmd[@]}" -g- "$filepath"
@@ -380,6 +388,14 @@ parse_requirements() {
     missing_deps=1
   else
     deps['mmsg']="$(command -v mmsg | head -n1)"
+  fi
+
+  # :dependency.filter
+  if ! command -v wayfreeze >/dev/null 2>&1; then
+    printf "missing dependency: wayfreeze\n" >&2
+    missing_deps=1
+  else
+    deps['wayfreeze']="$(command -v wayfreeze | head -n1)"
   fi
 
   if [[ -n $missing_deps ]]; then
